[build]
  publish = "playground/dist"
  command = "pnpm run dev:build"

[functions]
  directory = "playground/.netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
