blank_issues_enabled: true
contact_links:
  - name: 📚 @byjohann/nuxt-i18n Documentation
    url: https://github.com/johannschopplich/nuxt-i18n#readme
    about: Check the documentation for usage of @byjohann/nuxt-i18n
